name: resistohms
description: resistor color coding and ohms law calculator.



publish_to: 'none' 






version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.0
  flutter_circle_color_picker: ^0.2.0
  color_convert: ^1.0.2
  
  flutter_colorpicker: ^0.3.5
  
  flutter_snake_navigationbar: ^0.4.4
  
  shared_preferences: ^0.5.12+4
  
  firebase_admob: ^0.9.3
  flutter_automation: ^1.4.0
  flutter_launcher_icons: "^0.8.0"
  change_app_package_name: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true
   
  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: fonts/MyFlutterApp.ttf  
    - family:  ResistorColorCode
      fonts:
       - asset: fonts/ResistorColorCode.ttf   
    - family:  Smd
      fonts:
       - asset: fonts/Smd.ttf   
  
   
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
