/// Flutter icons ResistorColorCode
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ResistorColorCode
///      fonts:
///       - asset: fonts/ResistorColorCode.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ResistorColorCode {
  ResistorColorCode._();

  static const _kFontFam = 'ResistorColorCode';
  static const String _kFontPkg = null;

  static const IconData resistor_3_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
